name: TaskApp CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependencias
        run: npm install

      - name: Análisis estático
        run: npm run lint

      - name: Ejecutar pruebas
        run: npm test

      - name: Construir imagen Docker
        run: docker build -t carloscode1/taskapp:latest .

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publicar imagen en Docker Hub
        run: docker push carloscode1/taskapp:latest

      - name: Iniciar aplicación para monitoreo
        run: |
          docker run -d -p 3000:3000 --name taskapp-monitor carloscode1/taskapp:latest
          sleep 5

      - name: Verificar Health Check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health)

          if [ "$response" -eq 200 ]; then
            echo "Health Check OK - Aplicación funcionando correctamente"
          else
            echo "ALERTA: Health Check falló. Código HTTP: $response"
            exit 1
          fi

      - name: Mostrar logs de la aplicación
        if: always()
        run: docker logs taskapp-monitor

      - name: Detener aplicación
        if: always()
        run: docker rm -f taskapp-monitor